// GENERATED by scripts/prepare-media.mjs — do not edit by hand.
// Regenerate with: npm run media:prepare

export type GalleryCat = keyof typeof GALLERY_CATS;

export const GALLERY_CATS = {
  ortho: { th: 'จัดฟัน', en: 'Braces' },
  veneer: { th: 'วีเนียร์', en: 'Veneers' },
  whitening: { th: 'ฟอกสีฟัน', en: 'Whitening' },
  denture: { th: 'ฟันปลอม', en: 'Dentures' },
  bonding: { th: 'อุดฟัน', en: 'Bonding' },
  implant: { th: 'รากฟันเทียม', en: 'Implants' },
  review: { th: 'รีวิวรวมเคส', en: 'Case reviews' },
} as const;

export interface GalleryItem {
  img: string;
  cat: GalleryCat;
}

export const GALLERY: GalleryItem[] = [
  { img: 'gallery/ortho/003.webp', cat: 'ortho' },
  { img: 'gallery/ortho/009.webp', cat: 'ortho' },
  { img: 'gallery/ortho/010.webp', cat: 'ortho' },
  { img: 'gallery/ortho/015.webp', cat: 'ortho' },
  { img: 'gallery/ortho/017.webp', cat: 'ortho' },
  { img: 'gallery/ortho/027.webp', cat: 'ortho' },
  { img: 'gallery/ortho/050.webp', cat: 'ortho' },
  { img: 'gallery/ortho/069.webp', cat: 'ortho' },
  { img: 'gallery/ortho/074.webp', cat: 'ortho' },
  { img: 'gallery/ortho/075.webp', cat: 'ortho' },
  { img: 'gallery/veneer/001.webp', cat: 'veneer' },
  { img: 'gallery/veneer/002.webp', cat: 'veneer' },
  { img: 'gallery/veneer/003.webp', cat: 'veneer' },
  { img: 'gallery/veneer/004.webp', cat: 'veneer' },
  { img: 'gallery/veneer/005.webp', cat: 'veneer' },
  { img: 'gallery/veneer/006.webp', cat: 'veneer' },
  { img: 'gallery/veneer/007.webp', cat: 'veneer' },
  { img: 'gallery/veneer/008.webp', cat: 'veneer' },
  { img: 'gallery/veneer/009.webp', cat: 'veneer' },
  { img: 'gallery/veneer/010.webp', cat: 'veneer' },
  { img: 'gallery/whitening/001.webp', cat: 'whitening' },
  { img: 'gallery/whitening/002.webp', cat: 'whitening' },
  { img: 'gallery/whitening/003.webp', cat: 'whitening' },
  { img: 'gallery/whitening/004.webp', cat: 'whitening' },
  { img: 'gallery/whitening/005.webp', cat: 'whitening' },
  { img: 'gallery/denture/001.webp', cat: 'denture' },
  { img: 'gallery/denture/002.webp', cat: 'denture' },
  { img: 'gallery/bonding/001.webp', cat: 'bonding' },
  { img: 'gallery/bonding/002.webp', cat: 'bonding' },
  { img: 'gallery/bonding/003.webp', cat: 'bonding' },
  { img: 'gallery/bonding/006.webp', cat: 'bonding' },
  { img: 'gallery/bonding/007.webp', cat: 'bonding' },
  { img: 'gallery/bonding/008.webp', cat: 'bonding' },
  { img: 'gallery/bonding/009.webp', cat: 'bonding' },
  { img: 'gallery/bonding/010.webp', cat: 'bonding' },
  { img: 'gallery/bonding/011.webp', cat: 'bonding' },
  { img: 'gallery/bonding/012.webp', cat: 'bonding' },
  { img: 'gallery/bonding/013.webp', cat: 'bonding' },
  { img: 'gallery/bonding/014.webp', cat: 'bonding' },
  { img: 'gallery/bonding/018.webp', cat: 'bonding' },
  { img: 'gallery/bonding/019.webp', cat: 'bonding' },
  { img: 'gallery/bonding/020.webp', cat: 'bonding' },
  { img: 'gallery/bonding/021.webp', cat: 'bonding' },
  { img: 'gallery/bonding/022.webp', cat: 'bonding' },
  { img: 'gallery/bonding/023.webp', cat: 'bonding' },
  { img: 'gallery/bonding/024.webp', cat: 'bonding' },
  { img: 'gallery/bonding/025.webp', cat: 'bonding' },
  { img: 'gallery/bonding/026.webp', cat: 'bonding' },
  { img: 'gallery/implant/012.webp', cat: 'implant' },
  { img: 'gallery/implant/017.webp', cat: 'implant' },
  { img: 'gallery/review/003.webp', cat: 'review' },
  { img: 'gallery/review/008.webp', cat: 'review' },
  { img: 'gallery/review/009.webp', cat: 'review' },
  { img: 'gallery/review/010.webp', cat: 'review' },
];
